package ca.ontario.conestoga.volunteerhub.mapper;

import ca.ontario.conestoga.volunteerhub.entity.VolunteerReview;
import ca.ontario.conestoga.volunteerhub.entity.VolunteerReviewExample;
import ca.ontario.conestoga.volunteerhub.entity.VolunteerReviewKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VolunteerReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    long countByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int deleteByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int deleteByPrimaryKey(VolunteerReviewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int insert(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int insertSelective(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    List<VolunteerReview> selectByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    VolunteerReview selectByPrimaryKey(VolunteerReviewKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByExampleSelective(@Param("record") VolunteerReview record, @Param("example") VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByExample(@Param("record") VolunteerReview record, @Param("example") VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByPrimaryKeySelective(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByPrimaryKey(VolunteerReview record);
}