package ca.ontario.conestoga.volunteerhub.mapper;

import ca.ontario.conestoga.volunteerhub.entity.Volunteer;
import ca.ontario.conestoga.volunteerhub.entity.VolunteerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VolunteerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    long countByExample(VolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int deleteByExample(VolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int deleteByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int insert(Volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int insertSelective(Volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    List<Volunteer> selectByExample(VolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    Volunteer selectByPrimaryKey(Integer accountid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByExampleSelective(@Param("record") Volunteer record, @Param("example") VolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByExample(@Param("record") Volunteer record, @Param("example") VolunteerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByPrimaryKeySelective(Volunteer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    int updateByPrimaryKey(Volunteer record);
}