package ca.ontario.conestoga.volunteer_hub.entity;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.phone
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.email
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.organization_type
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private String organizationType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.phone
     *
     * @return the value of organization.phone
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.phone
     *
     * @param phone the value for organization.phone
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.email
     *
     * @return the value of organization.email
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.email
     *
     * @param email the value for organization.email
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.organization_type
     *
     * @return the value of organization.organization_type
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getOrganizationType() {
        return organizationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.organization_type
     *
     * @param organizationType the value for organization.organization_type
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setOrganizationType(String organizationType) {
        this.organizationType = organizationType == null ? null : organizationType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }
}