package ca.ontario.conestoga.volunteer_hub.entity;

public class Organization {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.logo_url
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.official_site_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String officialSiteLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column organization.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String postcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Organization(Integer id, String name, String logoUrl, String phone, String email, String officialSiteLink, String address, String postcode) {
        this.id = id;
        this.name = name;
        this.logoUrl = logoUrl;
        this.phone = phone;
        this.email = email;
        this.officialSiteLink = officialSiteLink;
        this.address = address;
        this.postcode = postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Organization() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.id
     *
     * @return the value of organization.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.id
     *
     * @param id the value for organization.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.name
     *
     * @return the value of organization.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.name
     *
     * @param name the value for organization.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.logo_url
     *
     * @return the value of organization.logo_url
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.logo_url
     *
     * @param logoUrl the value for organization.logo_url
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.phone
     *
     * @return the value of organization.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.phone
     *
     * @param phone the value for organization.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.email
     *
     * @return the value of organization.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.email
     *
     * @param email the value for organization.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.official_site_link
     *
     * @return the value of organization.official_site_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getOfficialSiteLink() {
        return officialSiteLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.official_site_link
     *
     * @param officialSiteLink the value for organization.official_site_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setOfficialSiteLink(String officialSiteLink) {
        this.officialSiteLink = officialSiteLink == null ? null : officialSiteLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.address
     *
     * @return the value of organization.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.address
     *
     * @param address the value for organization.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column organization.postcode
     *
     * @return the value of organization.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column organization.postcode
     *
     * @param postcode the value for organization.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }
}