package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.Date;

public class ParticipationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.event_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Integer eventId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.position_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.volunteer_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Integer volunteerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.participation_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Date participationTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.present
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Boolean present;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.arrive_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Date arriveTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.leave_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    private Date leaveTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation_record
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public ParticipationRecord(Integer id, Integer eventId, Integer positionId, Integer volunteerId, Date participationTime, Boolean present, Date arriveTime, Date leaveTime) {
        this.id = id;
        this.eventId = eventId;
        this.positionId = positionId;
        this.volunteerId = volunteerId;
        this.participationTime = participationTime;
        this.present = present;
        this.arriveTime = arriveTime;
        this.leaveTime = leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table participation_record
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public ParticipationRecord() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.id
     *
     * @return the value of participation_record.id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.id
     *
     * @param id the value for participation_record.id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.event_id
     *
     * @return the value of participation_record.event_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Integer getEventId() {
        return eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.event_id
     *
     * @param eventId the value for participation_record.event_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setEventId(Integer eventId) {
        this.eventId = eventId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.position_id
     *
     * @return the value of participation_record.position_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.position_id
     *
     * @param positionId the value for participation_record.position_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.volunteer_id
     *
     * @return the value of participation_record.volunteer_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Integer getVolunteerId() {
        return volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.volunteer_id
     *
     * @param volunteerId the value for participation_record.volunteer_id
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setVolunteerId(Integer volunteerId) {
        this.volunteerId = volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.participation_time
     *
     * @return the value of participation_record.participation_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Date getParticipationTime() {
        return participationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.participation_time
     *
     * @param participationTime the value for participation_record.participation_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setParticipationTime(Date participationTime) {
        this.participationTime = participationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.present
     *
     * @return the value of participation_record.present
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Boolean getPresent() {
        return present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.present
     *
     * @param present the value for participation_record.present
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setPresent(Boolean present) {
        this.present = present;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.arrive_time
     *
     * @return the value of participation_record.arrive_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Date getArriveTime() {
        return arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.arrive_time
     *
     * @param arriveTime the value for participation_record.arrive_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setArriveTime(Date arriveTime) {
        this.arriveTime = arriveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.leave_time
     *
     * @return the value of participation_record.leave_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public Date getLeaveTime() {
        return leaveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.leave_time
     *
     * @param leaveTime the value for participation_record.leave_time
     *
     * @mbg.generated Sun Jul 21 15:12:18 EDT 2024
     */
    public void setLeaveTime(Date leaveTime) {
        this.leaveTime = leaveTime;
    }
}