package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.Date;

public class ParticipationRecord {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.activity_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.volunteer_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private Integer volunteerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column participation_record.participation_time
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    private Date participationTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.id
     *
     * @return the value of participation_record.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.id
     *
     * @param id the value for participation_record.id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.activity_id
     *
     * @return the value of participation_record.activity_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.activity_id
     *
     * @param activityId the value for participation_record.activity_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.volunteer_id
     *
     * @return the value of participation_record.volunteer_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Integer getVolunteerId() {
        return volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.volunteer_id
     *
     * @param volunteerId the value for participation_record.volunteer_id
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setVolunteerId(Integer volunteerId) {
        this.volunteerId = volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column participation_record.participation_time
     *
     * @return the value of participation_record.participation_time
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Date getParticipationTime() {
        return participationTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column participation_record.participation_time
     *
     * @param participationTime the value for participation_record.participation_time
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setParticipationTime(Date participationTime) {
        this.participationTime = participationTime;
    }
}