package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.Date;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.id
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.username
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.commentDate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Date commentdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.comment
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String comment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.id
     *
     * @return the value of review.id
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.id
     *
     * @param id the value for review.id
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.accountId
     *
     * @return the value of review.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.accountId
     *
     * @param accountid the value for review.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.username
     *
     * @return the value of review.username
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.username
     *
     * @param username the value for review.username
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.commentDate
     *
     * @return the value of review.commentDate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Date getCommentdate() {
        return commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.commentDate
     *
     * @param commentdate the value for review.commentDate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setCommentdate(Date commentdate) {
        this.commentdate = commentdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.comment
     *
     * @return the value of review.comment
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getComment() {
        return comment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.comment
     *
     * @param comment the value for review.comment
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setComment(String comment) {
        this.comment = comment == null ? null : comment.trim();
    }
}