package ca.ontario.conestoga.volunteer_hub.entity;

public class VolunteerReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.volunteer_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Integer volunteerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.organization_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String organizationId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.organization_name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String organizationName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.id
     *
     * @return the value of volunteer_review.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.id
     *
     * @param id the value for volunteer_review.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.volunteer_id
     *
     * @return the value of volunteer_review.volunteer_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Integer getVolunteerId() {
        return volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.volunteer_id
     *
     * @param volunteerId the value for volunteer_review.volunteer_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setVolunteerId(Integer volunteerId) {
        this.volunteerId = volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.organization_id
     *
     * @return the value of volunteer_review.organization_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getOrganizationId() {
        return organizationId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.organization_id
     *
     * @param organizationId the value for volunteer_review.organization_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setOrganizationId(String organizationId) {
        this.organizationId = organizationId == null ? null : organizationId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.organization_name
     *
     * @return the value of volunteer_review.organization_name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getOrganizationName() {
        return organizationName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.organization_name
     *
     * @param organizationName the value for volunteer_review.organization_name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setOrganizationName(String organizationName) {
        this.organizationName = organizationName == null ? null : organizationName.trim();
    }
}