package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.ArrayList;
import java.util.List;

public class VolunteerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public VolunteerExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAccountidIsNull() {
            addCriterion("accountId is null");
            return (Criteria) this;
        }

        public Criteria andAccountidIsNotNull() {
            addCriterion("accountId is not null");
            return (Criteria) this;
        }

        public Criteria andAccountidEqualTo(Integer value) {
            addCriterion("accountId =", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotEqualTo(Integer value) {
            addCriterion("accountId <>", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThan(Integer value) {
            addCriterion("accountId >", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidGreaterThanOrEqualTo(Integer value) {
            addCriterion("accountId >=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThan(Integer value) {
            addCriterion("accountId <", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidLessThanOrEqualTo(Integer value) {
            addCriterion("accountId <=", value, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidIn(List<Integer> values) {
            addCriterion("accountId in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotIn(List<Integer> values) {
            addCriterion("accountId not in", values, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidBetween(Integer value1, Integer value2) {
            addCriterion("accountId between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andAccountidNotBetween(Integer value1, Integer value2) {
            addCriterion("accountId not between", value1, value2, "accountid");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIsNull() {
            addCriterion("maritalStatus is null");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIsNotNull() {
            addCriterion("maritalStatus is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusEqualTo(String value) {
            addCriterion("maritalStatus =", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotEqualTo(String value) {
            addCriterion("maritalStatus <>", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusGreaterThan(String value) {
            addCriterion("maritalStatus >", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusGreaterThanOrEqualTo(String value) {
            addCriterion("maritalStatus >=", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLessThan(String value) {
            addCriterion("maritalStatus <", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLessThanOrEqualTo(String value) {
            addCriterion("maritalStatus <=", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusLike(String value) {
            addCriterion("maritalStatus like", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotLike(String value) {
            addCriterion("maritalStatus not like", value, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusIn(List<String> values) {
            addCriterion("maritalStatus in", values, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotIn(List<String> values) {
            addCriterion("maritalStatus not in", values, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusBetween(String value1, String value2) {
            addCriterion("maritalStatus between", value1, value2, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andMaritalstatusNotBetween(String value1, String value2) {
            addCriterion("maritalStatus not between", value1, value2, "maritalstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusIsNull() {
            addCriterion("occupationStatus is null");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusIsNotNull() {
            addCriterion("occupationStatus is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusEqualTo(String value) {
            addCriterion("occupationStatus =", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusNotEqualTo(String value) {
            addCriterion("occupationStatus <>", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusGreaterThan(String value) {
            addCriterion("occupationStatus >", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusGreaterThanOrEqualTo(String value) {
            addCriterion("occupationStatus >=", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusLessThan(String value) {
            addCriterion("occupationStatus <", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusLessThanOrEqualTo(String value) {
            addCriterion("occupationStatus <=", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusLike(String value) {
            addCriterion("occupationStatus like", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusNotLike(String value) {
            addCriterion("occupationStatus not like", value, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusIn(List<String> values) {
            addCriterion("occupationStatus in", values, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusNotIn(List<String> values) {
            addCriterion("occupationStatus not in", values, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusBetween(String value1, String value2) {
            addCriterion("occupationStatus between", value1, value2, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andOccupationstatusNotBetween(String value1, String value2) {
            addCriterion("occupationStatus not between", value1, value2, "occupationstatus");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceIsNull() {
            addCriterion("hasDriversLicence is null");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceIsNotNull() {
            addCriterion("hasDriversLicence is not null");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceEqualTo(Boolean value) {
            addCriterion("hasDriversLicence =", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceNotEqualTo(Boolean value) {
            addCriterion("hasDriversLicence <>", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceGreaterThan(Boolean value) {
            addCriterion("hasDriversLicence >", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("hasDriversLicence >=", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceLessThan(Boolean value) {
            addCriterion("hasDriversLicence <", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceLessThanOrEqualTo(Boolean value) {
            addCriterion("hasDriversLicence <=", value, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceIn(List<Boolean> values) {
            addCriterion("hasDriversLicence in", values, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceNotIn(List<Boolean> values) {
            addCriterion("hasDriversLicence not in", values, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceBetween(Boolean value1, Boolean value2) {
            addCriterion("hasDriversLicence between", value1, value2, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andHasdriverslicenceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("hasDriversLicence not between", value1, value2, "hasdriverslicence");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNull() {
            addCriterion("skills is null");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNotNull() {
            addCriterion("skills is not null");
            return (Criteria) this;
        }

        public Criteria andSkillsEqualTo(String value) {
            addCriterion("skills =", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotEqualTo(String value) {
            addCriterion("skills <>", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThan(String value) {
            addCriterion("skills >", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThanOrEqualTo(String value) {
            addCriterion("skills >=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThan(String value) {
            addCriterion("skills <", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThanOrEqualTo(String value) {
            addCriterion("skills <=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLike(String value) {
            addCriterion("skills like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotLike(String value) {
            addCriterion("skills not like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsIn(List<String> values) {
            addCriterion("skills in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotIn(List<String> values) {
            addCriterion("skills not in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsBetween(String value1, String value2) {
            addCriterion("skills between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotBetween(String value1, String value2) {
            addCriterion("skills not between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateIsNull() {
            addCriterion("academicCertificate is null");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateIsNotNull() {
            addCriterion("academicCertificate is not null");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateEqualTo(String value) {
            addCriterion("academicCertificate =", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateNotEqualTo(String value) {
            addCriterion("academicCertificate <>", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateGreaterThan(String value) {
            addCriterion("academicCertificate >", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateGreaterThanOrEqualTo(String value) {
            addCriterion("academicCertificate >=", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateLessThan(String value) {
            addCriterion("academicCertificate <", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateLessThanOrEqualTo(String value) {
            addCriterion("academicCertificate <=", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateLike(String value) {
            addCriterion("academicCertificate like", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateNotLike(String value) {
            addCriterion("academicCertificate not like", value, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateIn(List<String> values) {
            addCriterion("academicCertificate in", values, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateNotIn(List<String> values) {
            addCriterion("academicCertificate not in", values, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateBetween(String value1, String value2) {
            addCriterion("academicCertificate between", value1, value2, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andAcademiccertificateNotBetween(String value1, String value2) {
            addCriterion("academicCertificate not between", value1, value2, "academiccertificate");
            return (Criteria) this;
        }

        public Criteria andResumelinkIsNull() {
            addCriterion("resumeLink is null");
            return (Criteria) this;
        }

        public Criteria andResumelinkIsNotNull() {
            addCriterion("resumeLink is not null");
            return (Criteria) this;
        }

        public Criteria andResumelinkEqualTo(String value) {
            addCriterion("resumeLink =", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkNotEqualTo(String value) {
            addCriterion("resumeLink <>", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkGreaterThan(String value) {
            addCriterion("resumeLink >", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkGreaterThanOrEqualTo(String value) {
            addCriterion("resumeLink >=", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkLessThan(String value) {
            addCriterion("resumeLink <", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkLessThanOrEqualTo(String value) {
            addCriterion("resumeLink <=", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkLike(String value) {
            addCriterion("resumeLink like", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkNotLike(String value) {
            addCriterion("resumeLink not like", value, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkIn(List<String> values) {
            addCriterion("resumeLink in", values, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkNotIn(List<String> values) {
            addCriterion("resumeLink not in", values, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkBetween(String value1, String value2) {
            addCriterion("resumeLink between", value1, value2, "resumelink");
            return (Criteria) this;
        }

        public Criteria andResumelinkNotBetween(String value1, String value2) {
            addCriterion("resumeLink not between", value1, value2, "resumelink");
            return (Criteria) this;
        }

        public Criteria andSkilltagsIsNull() {
            addCriterion("skillTags is null");
            return (Criteria) this;
        }

        public Criteria andSkilltagsIsNotNull() {
            addCriterion("skillTags is not null");
            return (Criteria) this;
        }

        public Criteria andSkilltagsEqualTo(String value) {
            addCriterion("skillTags =", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsNotEqualTo(String value) {
            addCriterion("skillTags <>", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsGreaterThan(String value) {
            addCriterion("skillTags >", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsGreaterThanOrEqualTo(String value) {
            addCriterion("skillTags >=", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsLessThan(String value) {
            addCriterion("skillTags <", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsLessThanOrEqualTo(String value) {
            addCriterion("skillTags <=", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsLike(String value) {
            addCriterion("skillTags like", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsNotLike(String value) {
            addCriterion("skillTags not like", value, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsIn(List<String> values) {
            addCriterion("skillTags in", values, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsNotIn(List<String> values) {
            addCriterion("skillTags not in", values, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsBetween(String value1, String value2) {
            addCriterion("skillTags between", value1, value2, "skilltags");
            return (Criteria) this;
        }

        public Criteria andSkilltagsNotBetween(String value1, String value2) {
            addCriterion("skillTags not between", value1, value2, "skilltags");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 14 13:55:17 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}