package ca.ontario.conestoga.volunteer_hub.entity;

public class Volunteer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.account_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Integer accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.age
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.gender
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.marital_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.occupation_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String occupationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.phone
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.email
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.address
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.has_drivers_licence
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private Boolean hasDriversLicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.skills
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String skills;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.academic_certificate
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String academicCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.resume_link
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String resumeLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.skill_tags
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    private String skillTags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.id
     *
     * @return the value of volunteer.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.id
     *
     * @param id the value for volunteer.id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.account_id
     *
     * @return the value of volunteer.account_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Integer getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.account_id
     *
     * @param accountId the value for volunteer.account_id
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setAccountId(Integer accountId) {
        this.accountId = accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.name
     *
     * @return the value of volunteer.name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.name
     *
     * @param name the value for volunteer.name
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.age
     *
     * @return the value of volunteer.age
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.age
     *
     * @param age the value for volunteer.age
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.gender
     *
     * @return the value of volunteer.gender
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.gender
     *
     * @param gender the value for volunteer.gender
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.marital_status
     *
     * @return the value of volunteer.marital_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.marital_status
     *
     * @param maritalStatus the value for volunteer.marital_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.occupation_status
     *
     * @return the value of volunteer.occupation_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getOccupationStatus() {
        return occupationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.occupation_status
     *
     * @param occupationStatus the value for volunteer.occupation_status
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setOccupationStatus(String occupationStatus) {
        this.occupationStatus = occupationStatus == null ? null : occupationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.phone
     *
     * @return the value of volunteer.phone
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.phone
     *
     * @param phone the value for volunteer.phone
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.email
     *
     * @return the value of volunteer.email
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.email
     *
     * @param email the value for volunteer.email
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.address
     *
     * @return the value of volunteer.address
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.address
     *
     * @param address the value for volunteer.address
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.has_drivers_licence
     *
     * @return the value of volunteer.has_drivers_licence
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public Boolean getHasDriversLicence() {
        return hasDriversLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.has_drivers_licence
     *
     * @param hasDriversLicence the value for volunteer.has_drivers_licence
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setHasDriversLicence(Boolean hasDriversLicence) {
        this.hasDriversLicence = hasDriversLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.skills
     *
     * @return the value of volunteer.skills
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.skills
     *
     * @param skills the value for volunteer.skills
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.academic_certificate
     *
     * @return the value of volunteer.academic_certificate
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getAcademicCertificate() {
        return academicCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.academic_certificate
     *
     * @param academicCertificate the value for volunteer.academic_certificate
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setAcademicCertificate(String academicCertificate) {
        this.academicCertificate = academicCertificate == null ? null : academicCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.resume_link
     *
     * @return the value of volunteer.resume_link
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getResumeLink() {
        return resumeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.resume_link
     *
     * @param resumeLink the value for volunteer.resume_link
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setResumeLink(String resumeLink) {
        this.resumeLink = resumeLink == null ? null : resumeLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.skill_tags
     *
     * @return the value of volunteer.skill_tags
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public String getSkillTags() {
        return skillTags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.skill_tags
     *
     * @param skillTags the value for volunteer.skill_tags
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    public void setSkillTags(String skillTags) {
        this.skillTags = skillTags == null ? null : skillTags.trim();
    }
}