package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.Date;

public class VolunteerReview {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.host_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String hostId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.volunteer_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Integer volunteerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.activity_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Integer activityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.review_time
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Date reviewTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public VolunteerReview(Integer id, String hostId, Integer volunteerId, Integer activityId, Date reviewTime) {
        this.id = id;
        this.hostId = hostId;
        this.volunteerId = volunteerId;
        this.activityId = activityId;
        this.reviewTime = reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public VolunteerReview() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.id
     *
     * @return the value of volunteer_review.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.id
     *
     * @param id the value for volunteer_review.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.host_id
     *
     * @return the value of volunteer_review.host_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getHostId() {
        return hostId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.host_id
     *
     * @param hostId the value for volunteer_review.host_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setHostId(String hostId) {
        this.hostId = hostId == null ? null : hostId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.volunteer_id
     *
     * @return the value of volunteer_review.volunteer_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Integer getVolunteerId() {
        return volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.volunteer_id
     *
     * @param volunteerId the value for volunteer_review.volunteer_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setVolunteerId(Integer volunteerId) {
        this.volunteerId = volunteerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.activity_id
     *
     * @return the value of volunteer_review.activity_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Integer getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.activity_id
     *
     * @param activityId the value for volunteer_review.activity_id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setActivityId(Integer activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.review_time
     *
     * @return the value of volunteer_review.review_time
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Date getReviewTime() {
        return reviewTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.review_time
     *
     * @param reviewTime the value for volunteer_review.review_time
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setReviewTime(Date reviewTime) {
        this.reviewTime = reviewTime;
    }
}