package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.Date;

public class Volunteer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.dob
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Date dob;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.sex
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.nationality
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String nationality;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.marital_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String maritalStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.occupation_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String occupationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String postcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.has_drivers_licence
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private Boolean hasDriversLicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.skills
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String skills;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.academic_certificate
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String academicCertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.resume_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    private String resumeLink;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Volunteer(Integer id, String name, Date dob, String sex, String nationality, String maritalStatus, String occupationStatus, String phone, String email, String address, String postcode, Boolean hasDriversLicence, String skills, String academicCertificate, String resumeLink) {
        this.id = id;
        this.name = name;
        this.dob = dob;
        this.sex = sex;
        this.nationality = nationality;
        this.maritalStatus = maritalStatus;
        this.occupationStatus = occupationStatus;
        this.phone = phone;
        this.email = email;
        this.address = address;
        this.postcode = postcode;
        this.hasDriversLicence = hasDriversLicence;
        this.skills = skills;
        this.academicCertificate = academicCertificate;
        this.resumeLink = resumeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Volunteer() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.id
     *
     * @return the value of volunteer.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.id
     *
     * @param id the value for volunteer.id
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.name
     *
     * @return the value of volunteer.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.name
     *
     * @param name the value for volunteer.name
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.dob
     *
     * @return the value of volunteer.dob
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Date getDob() {
        return dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.dob
     *
     * @param dob the value for volunteer.dob
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setDob(Date dob) {
        this.dob = dob;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.sex
     *
     * @return the value of volunteer.sex
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.sex
     *
     * @param sex the value for volunteer.sex
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.nationality
     *
     * @return the value of volunteer.nationality
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getNationality() {
        return nationality;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.nationality
     *
     * @param nationality the value for volunteer.nationality
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setNationality(String nationality) {
        this.nationality = nationality == null ? null : nationality.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.marital_status
     *
     * @return the value of volunteer.marital_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getMaritalStatus() {
        return maritalStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.marital_status
     *
     * @param maritalStatus the value for volunteer.marital_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus == null ? null : maritalStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.occupation_status
     *
     * @return the value of volunteer.occupation_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getOccupationStatus() {
        return occupationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.occupation_status
     *
     * @param occupationStatus the value for volunteer.occupation_status
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setOccupationStatus(String occupationStatus) {
        this.occupationStatus = occupationStatus == null ? null : occupationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.phone
     *
     * @return the value of volunteer.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.phone
     *
     * @param phone the value for volunteer.phone
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.email
     *
     * @return the value of volunteer.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.email
     *
     * @param email the value for volunteer.email
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.address
     *
     * @return the value of volunteer.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.address
     *
     * @param address the value for volunteer.address
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.postcode
     *
     * @return the value of volunteer.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getPostcode() {
        return postcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.postcode
     *
     * @param postcode the value for volunteer.postcode
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setPostcode(String postcode) {
        this.postcode = postcode == null ? null : postcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.has_drivers_licence
     *
     * @return the value of volunteer.has_drivers_licence
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public Boolean getHasDriversLicence() {
        return hasDriversLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.has_drivers_licence
     *
     * @param hasDriversLicence the value for volunteer.has_drivers_licence
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setHasDriversLicence(Boolean hasDriversLicence) {
        this.hasDriversLicence = hasDriversLicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.skills
     *
     * @return the value of volunteer.skills
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.skills
     *
     * @param skills the value for volunteer.skills
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.academic_certificate
     *
     * @return the value of volunteer.academic_certificate
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getAcademicCertificate() {
        return academicCertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.academic_certificate
     *
     * @param academicCertificate the value for volunteer.academic_certificate
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setAcademicCertificate(String academicCertificate) {
        this.academicCertificate = academicCertificate == null ? null : academicCertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.resume_link
     *
     * @return the value of volunteer.resume_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public String getResumeLink() {
        return resumeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.resume_link
     *
     * @param resumeLink the value for volunteer.resume_link
     *
     * @mbg.generated Sat Jul 20 19:03:30 EDT 2024
     */
    public void setResumeLink(String resumeLink) {
        this.resumeLink = resumeLink == null ? null : resumeLink.trim();
    }
}