package ca.ontario.conestoga.volunteer_hub.entity;

import java.util.ArrayList;
import java.util.List;

public class VolunteerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public VolunteerExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNull() {
            addCriterion("account_id is null");
            return (Criteria) this;
        }

        public Criteria andAccountIdIsNotNull() {
            addCriterion("account_id is not null");
            return (Criteria) this;
        }

        public Criteria andAccountIdEqualTo(Integer value) {
            addCriterion("account_id =", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotEqualTo(Integer value) {
            addCriterion("account_id <>", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThan(Integer value) {
            addCriterion("account_id >", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("account_id >=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThan(Integer value) {
            addCriterion("account_id <", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdLessThanOrEqualTo(Integer value) {
            addCriterion("account_id <=", value, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdIn(List<Integer> values) {
            addCriterion("account_id in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotIn(List<Integer> values) {
            addCriterion("account_id not in", values, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdBetween(Integer value1, Integer value2) {
            addCriterion("account_id between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andAccountIdNotBetween(Integer value1, Integer value2) {
            addCriterion("account_id not between", value1, value2, "accountId");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(String value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(String value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(String value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(String value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(String value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(String value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLike(String value) {
            addCriterion("gender like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotLike(String value) {
            addCriterion("gender not like", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<String> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<String> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(String value1, String value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(String value1, String value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNull() {
            addCriterion("marital_status is null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIsNotNull() {
            addCriterion("marital_status is not null");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusEqualTo(String value) {
            addCriterion("marital_status =", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotEqualTo(String value) {
            addCriterion("marital_status <>", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThan(String value) {
            addCriterion("marital_status >", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusGreaterThanOrEqualTo(String value) {
            addCriterion("marital_status >=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThan(String value) {
            addCriterion("marital_status <", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLessThanOrEqualTo(String value) {
            addCriterion("marital_status <=", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusLike(String value) {
            addCriterion("marital_status like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotLike(String value) {
            addCriterion("marital_status not like", value, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusIn(List<String> values) {
            addCriterion("marital_status in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotIn(List<String> values) {
            addCriterion("marital_status not in", values, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusBetween(String value1, String value2) {
            addCriterion("marital_status between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andMaritalStatusNotBetween(String value1, String value2) {
            addCriterion("marital_status not between", value1, value2, "maritalStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusIsNull() {
            addCriterion("occupation_status is null");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusIsNotNull() {
            addCriterion("occupation_status is not null");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusEqualTo(String value) {
            addCriterion("occupation_status =", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusNotEqualTo(String value) {
            addCriterion("occupation_status <>", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusGreaterThan(String value) {
            addCriterion("occupation_status >", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusGreaterThanOrEqualTo(String value) {
            addCriterion("occupation_status >=", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusLessThan(String value) {
            addCriterion("occupation_status <", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusLessThanOrEqualTo(String value) {
            addCriterion("occupation_status <=", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusLike(String value) {
            addCriterion("occupation_status like", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusNotLike(String value) {
            addCriterion("occupation_status not like", value, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusIn(List<String> values) {
            addCriterion("occupation_status in", values, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusNotIn(List<String> values) {
            addCriterion("occupation_status not in", values, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusBetween(String value1, String value2) {
            addCriterion("occupation_status between", value1, value2, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andOccupationStatusNotBetween(String value1, String value2) {
            addCriterion("occupation_status not between", value1, value2, "occupationStatus");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceIsNull() {
            addCriterion("has_drivers_licence is null");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceIsNotNull() {
            addCriterion("has_drivers_licence is not null");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceEqualTo(Boolean value) {
            addCriterion("has_drivers_licence =", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceNotEqualTo(Boolean value) {
            addCriterion("has_drivers_licence <>", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceGreaterThan(Boolean value) {
            addCriterion("has_drivers_licence >", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceGreaterThanOrEqualTo(Boolean value) {
            addCriterion("has_drivers_licence >=", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceLessThan(Boolean value) {
            addCriterion("has_drivers_licence <", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceLessThanOrEqualTo(Boolean value) {
            addCriterion("has_drivers_licence <=", value, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceIn(List<Boolean> values) {
            addCriterion("has_drivers_licence in", values, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceNotIn(List<Boolean> values) {
            addCriterion("has_drivers_licence not in", values, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceBetween(Boolean value1, Boolean value2) {
            addCriterion("has_drivers_licence between", value1, value2, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andHasDriversLicenceNotBetween(Boolean value1, Boolean value2) {
            addCriterion("has_drivers_licence not between", value1, value2, "hasDriversLicence");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNull() {
            addCriterion("skills is null");
            return (Criteria) this;
        }

        public Criteria andSkillsIsNotNull() {
            addCriterion("skills is not null");
            return (Criteria) this;
        }

        public Criteria andSkillsEqualTo(String value) {
            addCriterion("skills =", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotEqualTo(String value) {
            addCriterion("skills <>", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThan(String value) {
            addCriterion("skills >", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsGreaterThanOrEqualTo(String value) {
            addCriterion("skills >=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThan(String value) {
            addCriterion("skills <", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLessThanOrEqualTo(String value) {
            addCriterion("skills <=", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsLike(String value) {
            addCriterion("skills like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotLike(String value) {
            addCriterion("skills not like", value, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsIn(List<String> values) {
            addCriterion("skills in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotIn(List<String> values) {
            addCriterion("skills not in", values, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsBetween(String value1, String value2) {
            addCriterion("skills between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andSkillsNotBetween(String value1, String value2) {
            addCriterion("skills not between", value1, value2, "skills");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateIsNull() {
            addCriterion("academic_certificate is null");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateIsNotNull() {
            addCriterion("academic_certificate is not null");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateEqualTo(String value) {
            addCriterion("academic_certificate =", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateNotEqualTo(String value) {
            addCriterion("academic_certificate <>", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateGreaterThan(String value) {
            addCriterion("academic_certificate >", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateGreaterThanOrEqualTo(String value) {
            addCriterion("academic_certificate >=", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateLessThan(String value) {
            addCriterion("academic_certificate <", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateLessThanOrEqualTo(String value) {
            addCriterion("academic_certificate <=", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateLike(String value) {
            addCriterion("academic_certificate like", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateNotLike(String value) {
            addCriterion("academic_certificate not like", value, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateIn(List<String> values) {
            addCriterion("academic_certificate in", values, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateNotIn(List<String> values) {
            addCriterion("academic_certificate not in", values, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateBetween(String value1, String value2) {
            addCriterion("academic_certificate between", value1, value2, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andAcademicCertificateNotBetween(String value1, String value2) {
            addCriterion("academic_certificate not between", value1, value2, "academicCertificate");
            return (Criteria) this;
        }

        public Criteria andResumeLinkIsNull() {
            addCriterion("resume_link is null");
            return (Criteria) this;
        }

        public Criteria andResumeLinkIsNotNull() {
            addCriterion("resume_link is not null");
            return (Criteria) this;
        }

        public Criteria andResumeLinkEqualTo(String value) {
            addCriterion("resume_link =", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkNotEqualTo(String value) {
            addCriterion("resume_link <>", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkGreaterThan(String value) {
            addCriterion("resume_link >", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkGreaterThanOrEqualTo(String value) {
            addCriterion("resume_link >=", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkLessThan(String value) {
            addCriterion("resume_link <", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkLessThanOrEqualTo(String value) {
            addCriterion("resume_link <=", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkLike(String value) {
            addCriterion("resume_link like", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkNotLike(String value) {
            addCriterion("resume_link not like", value, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkIn(List<String> values) {
            addCriterion("resume_link in", values, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkNotIn(List<String> values) {
            addCriterion("resume_link not in", values, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkBetween(String value1, String value2) {
            addCriterion("resume_link between", value1, value2, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andResumeLinkNotBetween(String value1, String value2) {
            addCriterion("resume_link not between", value1, value2, "resumeLink");
            return (Criteria) this;
        }

        public Criteria andSkillTagsIsNull() {
            addCriterion("skill_tags is null");
            return (Criteria) this;
        }

        public Criteria andSkillTagsIsNotNull() {
            addCriterion("skill_tags is not null");
            return (Criteria) this;
        }

        public Criteria andSkillTagsEqualTo(String value) {
            addCriterion("skill_tags =", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsNotEqualTo(String value) {
            addCriterion("skill_tags <>", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsGreaterThan(String value) {
            addCriterion("skill_tags >", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsGreaterThanOrEqualTo(String value) {
            addCriterion("skill_tags >=", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsLessThan(String value) {
            addCriterion("skill_tags <", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsLessThanOrEqualTo(String value) {
            addCriterion("skill_tags <=", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsLike(String value) {
            addCriterion("skill_tags like", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsNotLike(String value) {
            addCriterion("skill_tags not like", value, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsIn(List<String> values) {
            addCriterion("skill_tags in", values, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsNotIn(List<String> values) {
            addCriterion("skill_tags not in", values, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsBetween(String value1, String value2) {
            addCriterion("skill_tags between", value1, value2, "skillTags");
            return (Criteria) this;
        }

        public Criteria andSkillTagsNotBetween(String value1, String value2) {
            addCriterion("skill_tags not between", value1, value2, "skillTags");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 05 12:13:26 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}