package ca.ontario.conestoga.volunteerhub.entity;

public class Volunteer {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Integer accountid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.name
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.age
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.gender
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.maritalStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String maritalstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.occupationStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String occupationstatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.phone
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.email
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.address
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.hasDriversLicence
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Boolean hasdriverslicence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.skills
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String skills;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.academicCertificate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String academiccertificate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.resumeLink
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String resumelink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer.skillTags
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String skilltags;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.accountId
     *
     * @return the value of volunteer.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Integer getAccountid() {
        return accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.accountId
     *
     * @param accountid the value for volunteer.accountId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setAccountid(Integer accountid) {
        this.accountid = accountid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.name
     *
     * @return the value of volunteer.name
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.name
     *
     * @param name the value for volunteer.name
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.age
     *
     * @return the value of volunteer.age
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.age
     *
     * @param age the value for volunteer.age
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.gender
     *
     * @return the value of volunteer.gender
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.gender
     *
     * @param gender the value for volunteer.gender
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.maritalStatus
     *
     * @return the value of volunteer.maritalStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getMaritalstatus() {
        return maritalstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.maritalStatus
     *
     * @param maritalstatus the value for volunteer.maritalStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setMaritalstatus(String maritalstatus) {
        this.maritalstatus = maritalstatus == null ? null : maritalstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.occupationStatus
     *
     * @return the value of volunteer.occupationStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getOccupationstatus() {
        return occupationstatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.occupationStatus
     *
     * @param occupationstatus the value for volunteer.occupationStatus
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setOccupationstatus(String occupationstatus) {
        this.occupationstatus = occupationstatus == null ? null : occupationstatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.phone
     *
     * @return the value of volunteer.phone
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.phone
     *
     * @param phone the value for volunteer.phone
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.email
     *
     * @return the value of volunteer.email
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.email
     *
     * @param email the value for volunteer.email
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.address
     *
     * @return the value of volunteer.address
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.address
     *
     * @param address the value for volunteer.address
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.hasDriversLicence
     *
     * @return the value of volunteer.hasDriversLicence
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Boolean getHasdriverslicence() {
        return hasdriverslicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.hasDriversLicence
     *
     * @param hasdriverslicence the value for volunteer.hasDriversLicence
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setHasdriverslicence(Boolean hasdriverslicence) {
        this.hasdriverslicence = hasdriverslicence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.skills
     *
     * @return the value of volunteer.skills
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getSkills() {
        return skills;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.skills
     *
     * @param skills the value for volunteer.skills
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setSkills(String skills) {
        this.skills = skills == null ? null : skills.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.academicCertificate
     *
     * @return the value of volunteer.academicCertificate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getAcademiccertificate() {
        return academiccertificate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.academicCertificate
     *
     * @param academiccertificate the value for volunteer.academicCertificate
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setAcademiccertificate(String academiccertificate) {
        this.academiccertificate = academiccertificate == null ? null : academiccertificate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.resumeLink
     *
     * @return the value of volunteer.resumeLink
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getResumelink() {
        return resumelink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.resumeLink
     *
     * @param resumelink the value for volunteer.resumeLink
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setResumelink(String resumelink) {
        this.resumelink = resumelink == null ? null : resumelink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer.skillTags
     *
     * @return the value of volunteer.skillTags
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getSkilltags() {
        return skilltags;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer.skillTags
     *
     * @param skilltags the value for volunteer.skillTags
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setSkilltags(String skilltags) {
        this.skilltags = skilltags == null ? null : skilltags.trim();
    }
}