package ca.ontario.conestoga.volunteerhub.entity;

public class VolunteerReviewKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.volunteerId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private Integer volunteerid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column volunteer_review.organizationId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    private String organizationid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.volunteerId
     *
     * @return the value of volunteer_review.volunteerId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Integer getVolunteerid() {
        return volunteerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.volunteerId
     *
     * @param volunteerid the value for volunteer_review.volunteerId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setVolunteerid(Integer volunteerid) {
        this.volunteerid = volunteerid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column volunteer_review.organizationId
     *
     * @return the value of volunteer_review.organizationId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getOrganizationid() {
        return organizationid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column volunteer_review.organizationId
     *
     * @param organizationid the value for volunteer_review.organizationId
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setOrganizationid(String organizationid) {
        this.organizationid = organizationid == null ? null : organizationid.trim();
    }
}