package ca.ontario.conestoga.volunteerhub.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class VolunteerActivityExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public VolunteerActivityExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNull() {
            addCriterion("subtitle is null");
            return (Criteria) this;
        }

        public Criteria andSubtitleIsNotNull() {
            addCriterion("subtitle is not null");
            return (Criteria) this;
        }

        public Criteria andSubtitleEqualTo(String value) {
            addCriterion("subtitle =", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotEqualTo(String value) {
            addCriterion("subtitle <>", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThan(String value) {
            addCriterion("subtitle >", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleGreaterThanOrEqualTo(String value) {
            addCriterion("subtitle >=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThan(String value) {
            addCriterion("subtitle <", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLessThanOrEqualTo(String value) {
            addCriterion("subtitle <=", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleLike(String value) {
            addCriterion("subtitle like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotLike(String value) {
            addCriterion("subtitle not like", value, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleIn(List<String> values) {
            addCriterion("subtitle in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotIn(List<String> values) {
            addCriterion("subtitle not in", values, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleBetween(String value1, String value2) {
            addCriterion("subtitle between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andSubtitleNotBetween(String value1, String value2) {
            addCriterion("subtitle not between", value1, value2, "subtitle");
            return (Criteria) this;
        }

        public Criteria andImgsIsNull() {
            addCriterion("imgs is null");
            return (Criteria) this;
        }

        public Criteria andImgsIsNotNull() {
            addCriterion("imgs is not null");
            return (Criteria) this;
        }

        public Criteria andImgsEqualTo(String value) {
            addCriterion("imgs =", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotEqualTo(String value) {
            addCriterion("imgs <>", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThan(String value) {
            addCriterion("imgs >", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsGreaterThanOrEqualTo(String value) {
            addCriterion("imgs >=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThan(String value) {
            addCriterion("imgs <", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLessThanOrEqualTo(String value) {
            addCriterion("imgs <=", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsLike(String value) {
            addCriterion("imgs like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotLike(String value) {
            addCriterion("imgs not like", value, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsIn(List<String> values) {
            addCriterion("imgs in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotIn(List<String> values) {
            addCriterion("imgs not in", values, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsBetween(String value1, String value2) {
            addCriterion("imgs between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andImgsNotBetween(String value1, String value2) {
            addCriterion("imgs not between", value1, value2, "imgs");
            return (Criteria) this;
        }

        public Criteria andHostidIsNull() {
            addCriterion("hostId is null");
            return (Criteria) this;
        }

        public Criteria andHostidIsNotNull() {
            addCriterion("hostId is not null");
            return (Criteria) this;
        }

        public Criteria andHostidEqualTo(String value) {
            addCriterion("hostId =", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidNotEqualTo(String value) {
            addCriterion("hostId <>", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidGreaterThan(String value) {
            addCriterion("hostId >", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidGreaterThanOrEqualTo(String value) {
            addCriterion("hostId >=", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidLessThan(String value) {
            addCriterion("hostId <", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidLessThanOrEqualTo(String value) {
            addCriterion("hostId <=", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidLike(String value) {
            addCriterion("hostId like", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidNotLike(String value) {
            addCriterion("hostId not like", value, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidIn(List<String> values) {
            addCriterion("hostId in", values, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidNotIn(List<String> values) {
            addCriterion("hostId not in", values, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidBetween(String value1, String value2) {
            addCriterion("hostId between", value1, value2, "hostid");
            return (Criteria) this;
        }

        public Criteria andHostidNotBetween(String value1, String value2) {
            addCriterion("hostId not between", value1, value2, "hostid");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeIsNull() {
            addCriterion("launchTime is null");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeIsNotNull() {
            addCriterion("launchTime is not null");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeEqualTo(Date value) {
            addCriterion("launchTime =", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeNotEqualTo(Date value) {
            addCriterion("launchTime <>", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeGreaterThan(Date value) {
            addCriterion("launchTime >", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("launchTime >=", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeLessThan(Date value) {
            addCriterion("launchTime <", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeLessThanOrEqualTo(Date value) {
            addCriterion("launchTime <=", value, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeIn(List<Date> values) {
            addCriterion("launchTime in", values, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeNotIn(List<Date> values) {
            addCriterion("launchTime not in", values, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeBetween(Date value1, Date value2) {
            addCriterion("launchTime between", value1, value2, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLaunchtimeNotBetween(Date value1, Date value2) {
            addCriterion("launchTime not between", value1, value2, "launchtime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeIsNull() {
            addCriterion("lastEditTime is null");
            return (Criteria) this;
        }

        public Criteria andLastedittimeIsNotNull() {
            addCriterion("lastEditTime is not null");
            return (Criteria) this;
        }

        public Criteria andLastedittimeEqualTo(Date value) {
            addCriterion("lastEditTime =", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeNotEqualTo(Date value) {
            addCriterion("lastEditTime <>", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeGreaterThan(Date value) {
            addCriterion("lastEditTime >", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeGreaterThanOrEqualTo(Date value) {
            addCriterion("lastEditTime >=", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeLessThan(Date value) {
            addCriterion("lastEditTime <", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeLessThanOrEqualTo(Date value) {
            addCriterion("lastEditTime <=", value, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeIn(List<Date> values) {
            addCriterion("lastEditTime in", values, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeNotIn(List<Date> values) {
            addCriterion("lastEditTime not in", values, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeBetween(Date value1, Date value2) {
            addCriterion("lastEditTime between", value1, value2, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLastedittimeNotBetween(Date value1, Date value2) {
            addCriterion("lastEditTime not between", value1, value2, "lastedittime");
            return (Criteria) this;
        }

        public Criteria andLikesnumIsNull() {
            addCriterion("likesNum is null");
            return (Criteria) this;
        }

        public Criteria andLikesnumIsNotNull() {
            addCriterion("likesNum is not null");
            return (Criteria) this;
        }

        public Criteria andLikesnumEqualTo(Integer value) {
            addCriterion("likesNum =", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumNotEqualTo(Integer value) {
            addCriterion("likesNum <>", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumGreaterThan(Integer value) {
            addCriterion("likesNum >", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("likesNum >=", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumLessThan(Integer value) {
            addCriterion("likesNum <", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumLessThanOrEqualTo(Integer value) {
            addCriterion("likesNum <=", value, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumIn(List<Integer> values) {
            addCriterion("likesNum in", values, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumNotIn(List<Integer> values) {
            addCriterion("likesNum not in", values, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumBetween(Integer value1, Integer value2) {
            addCriterion("likesNum between", value1, value2, "likesnum");
            return (Criteria) this;
        }

        public Criteria andLikesnumNotBetween(Integer value1, Integer value2) {
            addCriterion("likesNum not between", value1, value2, "likesnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumIsNull() {
            addCriterion("collectionsNum is null");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumIsNotNull() {
            addCriterion("collectionsNum is not null");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumEqualTo(Integer value) {
            addCriterion("collectionsNum =", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumNotEqualTo(Integer value) {
            addCriterion("collectionsNum <>", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumGreaterThan(Integer value) {
            addCriterion("collectionsNum >", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("collectionsNum >=", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumLessThan(Integer value) {
            addCriterion("collectionsNum <", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumLessThanOrEqualTo(Integer value) {
            addCriterion("collectionsNum <=", value, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumIn(List<Integer> values) {
            addCriterion("collectionsNum in", values, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumNotIn(List<Integer> values) {
            addCriterion("collectionsNum not in", values, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumBetween(Integer value1, Integer value2) {
            addCriterion("collectionsNum between", value1, value2, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andCollectionsnumNotBetween(Integer value1, Integer value2) {
            addCriterion("collectionsNum not between", value1, value2, "collectionsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumIsNull() {
            addCriterion("reviewsNum is null");
            return (Criteria) this;
        }

        public Criteria andReviewsnumIsNotNull() {
            addCriterion("reviewsNum is not null");
            return (Criteria) this;
        }

        public Criteria andReviewsnumEqualTo(Integer value) {
            addCriterion("reviewsNum =", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumNotEqualTo(Integer value) {
            addCriterion("reviewsNum <>", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumGreaterThan(Integer value) {
            addCriterion("reviewsNum >", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("reviewsNum >=", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumLessThan(Integer value) {
            addCriterion("reviewsNum <", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumLessThanOrEqualTo(Integer value) {
            addCriterion("reviewsNum <=", value, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumIn(List<Integer> values) {
            addCriterion("reviewsNum in", values, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumNotIn(List<Integer> values) {
            addCriterion("reviewsNum not in", values, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumBetween(Integer value1, Integer value2) {
            addCriterion("reviewsNum between", value1, value2, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andReviewsnumNotBetween(Integer value1, Integer value2) {
            addCriterion("reviewsNum not between", value1, value2, "reviewsnum");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsIsNull() {
            addCriterion("requiredSkillTags is null");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsIsNotNull() {
            addCriterion("requiredSkillTags is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsEqualTo(String value) {
            addCriterion("requiredSkillTags =", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsNotEqualTo(String value) {
            addCriterion("requiredSkillTags <>", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsGreaterThan(String value) {
            addCriterion("requiredSkillTags >", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsGreaterThanOrEqualTo(String value) {
            addCriterion("requiredSkillTags >=", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsLessThan(String value) {
            addCriterion("requiredSkillTags <", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsLessThanOrEqualTo(String value) {
            addCriterion("requiredSkillTags <=", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsLike(String value) {
            addCriterion("requiredSkillTags like", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsNotLike(String value) {
            addCriterion("requiredSkillTags not like", value, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsIn(List<String> values) {
            addCriterion("requiredSkillTags in", values, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsNotIn(List<String> values) {
            addCriterion("requiredSkillTags not in", values, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsBetween(String value1, String value2) {
            addCriterion("requiredSkillTags between", value1, value2, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andRequiredskilltagsNotBetween(String value1, String value2) {
            addCriterion("requiredSkillTags not between", value1, value2, "requiredskilltags");
            return (Criteria) this;
        }

        public Criteria andVenueIsNull() {
            addCriterion("venue is null");
            return (Criteria) this;
        }

        public Criteria andVenueIsNotNull() {
            addCriterion("venue is not null");
            return (Criteria) this;
        }

        public Criteria andVenueEqualTo(String value) {
            addCriterion("venue =", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueNotEqualTo(String value) {
            addCriterion("venue <>", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueGreaterThan(String value) {
            addCriterion("venue >", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueGreaterThanOrEqualTo(String value) {
            addCriterion("venue >=", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueLessThan(String value) {
            addCriterion("venue <", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueLessThanOrEqualTo(String value) {
            addCriterion("venue <=", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueLike(String value) {
            addCriterion("venue like", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueNotLike(String value) {
            addCriterion("venue not like", value, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueIn(List<String> values) {
            addCriterion("venue in", values, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueNotIn(List<String> values) {
            addCriterion("venue not in", values, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueBetween(String value1, String value2) {
            addCriterion("venue between", value1, value2, "venue");
            return (Criteria) this;
        }

        public Criteria andVenueNotBetween(String value1, String value2) {
            addCriterion("venue not between", value1, value2, "venue");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIsNull() {
            addCriterion("activityStartTime is null");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIsNotNull() {
            addCriterion("activityStartTime is not null");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeEqualTo(Date value) {
            addCriterion("activityStartTime =", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotEqualTo(Date value) {
            addCriterion("activityStartTime <>", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeGreaterThan(Date value) {
            addCriterion("activityStartTime >", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activityStartTime >=", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeLessThan(Date value) {
            addCriterion("activityStartTime <", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeLessThanOrEqualTo(Date value) {
            addCriterion("activityStartTime <=", value, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeIn(List<Date> values) {
            addCriterion("activityStartTime in", values, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotIn(List<Date> values) {
            addCriterion("activityStartTime not in", values, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeBetween(Date value1, Date value2) {
            addCriterion("activityStartTime between", value1, value2, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivitystarttimeNotBetween(Date value1, Date value2) {
            addCriterion("activityStartTime not between", value1, value2, "activitystarttime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIsNull() {
            addCriterion("activityEndTime is null");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIsNotNull() {
            addCriterion("activityEndTime is not null");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeEqualTo(Date value) {
            addCriterion("activityEndTime =", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotEqualTo(Date value) {
            addCriterion("activityEndTime <>", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeGreaterThan(Date value) {
            addCriterion("activityEndTime >", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activityEndTime >=", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeLessThan(Date value) {
            addCriterion("activityEndTime <", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeLessThanOrEqualTo(Date value) {
            addCriterion("activityEndTime <=", value, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeIn(List<Date> values) {
            addCriterion("activityEndTime in", values, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotIn(List<Date> values) {
            addCriterion("activityEndTime not in", values, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeBetween(Date value1, Date value2) {
            addCriterion("activityEndTime between", value1, value2, "activityendtime");
            return (Criteria) this;
        }

        public Criteria andActivityendtimeNotBetween(Date value1, Date value2) {
            addCriterion("activityEndTime not between", value1, value2, "activityendtime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer_activity
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 14 13:55:17 EDT 2024
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jun 14 13:55:17 EDT 2024
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}