package ca.ontario.conestoga.volunteer_hub.mapper;

import ca.ontario.conestoga.volunteer_hub.entity.ActivitiesReview;
import ca.ontario.conestoga.volunteer_hub.entity.ActivitiesReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ActivitiesReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    long countByExample(ActivitiesReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int deleteByExample(ActivitiesReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int insert(ActivitiesReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int insertSelective(ActivitiesReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    List<ActivitiesReview> selectByExample(ActivitiesReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    ActivitiesReview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByExampleSelective(@Param("record") ActivitiesReview record, @Param("example") ActivitiesReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByExample(@Param("record") ActivitiesReview record, @Param("example") ActivitiesReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByPrimaryKeySelective(ActivitiesReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table activities_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByPrimaryKey(ActivitiesReview record);
}