package ca.ontario.conestoga.volunteer_hub.mapper;

import ca.ontario.conestoga.volunteer_hub.entity.VolunteerReview;
import ca.ontario.conestoga.volunteer_hub.entity.VolunteerReviewExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VolunteerReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    long countByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int deleteByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int insert(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int insertSelective(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    List<VolunteerReview> selectByExample(VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    VolunteerReview selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByExampleSelective(@Param("record") VolunteerReview record, @Param("example") VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByExample(@Param("record") VolunteerReview record, @Param("example") VolunteerReviewExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByPrimaryKeySelective(VolunteerReview record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_review
     *
     * @mbg.generated Thu Jun 27 16:25:21 EDT 2024
     */
    int updateByPrimaryKey(VolunteerReview record);
}