package ca.ontario.conestoga.volunteer_hub.mapper;

import ca.ontario.conestoga.volunteer_hub.entity.VolunteerActivity;
import ca.ontario.conestoga.volunteer_hub.entity.VolunteerActivityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface VolunteerActivityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    long countByExample(VolunteerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int deleteByExample(VolunteerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int insert(VolunteerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int insertSelective(VolunteerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    List<VolunteerActivity> selectByExample(VolunteerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    VolunteerActivity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int updateByExampleSelective(@Param("record") VolunteerActivity record, @Param("example") VolunteerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int updateByExample(@Param("record") VolunteerActivity record, @Param("example") VolunteerActivityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int updateByPrimaryKeySelective(VolunteerActivity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table volunteer_activity
     *
     * @mbg.generated Fri Jul 05 12:13:26 EDT 2024
     */
    int updateByPrimaryKey(VolunteerActivity record);
}